CREATE TABLE Products (
	Id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	Name NVARCHAR(120) NOT NULL,
	Price DECIMAL(18,2) NOT NULL,
	Stock INT NOT NULL,
	CreatedAt DATETIME NOT NULL DEFAULT GETDATE()
)

INSERT INTO Products(Name, Price, Stock) VALUES('Galletas Oreo', 2500, 10)
INSERT INTO Products(Name, Price, Stock) VALUES('Pepsi 3 Litros', 5000, 8)
INSERT INTO Products(Name, Price, Stock) VALUES('DeTodito', 3500, 6)

CREATE TABLE Orders (
	Id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	CustomerName NVARCHAR(120) NOT NULL,
	CreatedAt DATETIME NOT NULL DEFAULT GETDATE()
)

CREATE TABLE OrderItems (
	Id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	ProductId INT NOT NULL,
	OrderId INT NOT NULL,
	Quantity INT NOT NULL,
	UnitPrice DECIMAL(18,2) NOT NULL,
	CONSTRAINT FK_OrderItems_Product FOREIGN KEY (ProductId) REFERENCES Products(Id),
	CONSTRAINT FK_OrderItems_Order FOREIGN KEY (OrderId) REFERENCES Orders(Id)
)